### ISSUE TITLE
不支持 picgo 的相册功能吗?

### ISSUE THREAD

**Issue by NanerLee** [xlzy520/picgo-plugin-smms-user#2]
相册界面选择图床那里会显示无数据, 不能查看以前自己上传的图片

**Comment by xlzy520** [comment]
@NanerLee 你的意思是上传的图片没有记录在data.json，还是不能查看以前在其他地方上传到smms的图片

**Comment by NanerLee** [comment]
@xlzy520 不能查看以前在其他地方上传的图片, 我看sm.ms api是支持查询用户的上传历史的.

难道那个相册功能只是记录通过 picgo 上传的图片吗?

**Comment by xlzy520** [comment]
@NanerLee 是的，你可以fork他的picgo，自己改造一下相册，加一个查看所有上传的图片的功能。本来我是打算做的，后来不用smms了，速度太慢了

**Comment by NanerLee** [comment]
哦哦, 是我理解错了, 我只用一些小图片, smms 速度还好.

我的技术栈估计改这个程序有些困难, 不过还是感谢你写的这个插件

**Comment by xlzy520** [comment]
@NanerLee 推荐你用下我写的浏览器插件，哔哩哔哩图床:blush:[下载](https://github.com/xlzy520/bilibili-img-uploader/releases)
完成了基本功能。
