### ISSUE TITLE
增加设置上传后的图片文件名功能

### ISSUE THREAD

**Issue by yf-9186** [xlzy520/picgo-plugin-smms-user#3]
目前上传后获取到的链接中的图片文件名是一串随机字符。不知道是否可以实现上传后的文件名保持原文件名不变，或者更进一步，可以自定义配置命名规则

**Comment by xlzy520** [comment]
你说的是相册中展示的文件名是不对的吗？是被picgo改成时间戳了？你发个截图看看
![image](https://user-images.githubusercontent.com/28336270/71889337-e53e6a00-317c-11ea-919b-b1288e71bb20.png)

**Comment by xlzy520** [comment]
我是觉得smms太慢了，还没有自定义图片质量样式，所以我又写了个浏览器插件，用的哔哩哔哩图床

**Comment by yf-9186** [comment]
![图片](https://user-images.githubusercontent.com/38492750/71890103-8d086780-317e-11ea-85d3-e514d0428e10.png)
如上图我的图片本来的文件名是IMG_0721.jpg，上传以后复制的链接是`![](https://i.loli.net/2020/01/07/N3HqO7ozKwWb5SY.jpg)`，里面的文件名就变成了N3HqO7ozKwWb5SY.jpg。能否保持原文件名不变。或者添加一些设置项，能够设定文件命名规则。

**Comment by xlzy520** [comment]
这个是smms的规则，不是picgo能管的，因为他要通过hash值来判断两个文件是不是同一个文件，所以不会用之前的文件名的。

**Comment by xlzy520** [comment]
https://github.com/xlzy520/bilibili-img-uploader
我来推销自己的B站插件了，速度要快很多倍，还可以自定义图片质量

**Comment by yf-9186** [comment]
> 
> 
> https://github.com/xlzy520/bilibili-img-uploader
> 我来推销自己的B站插件了，速度要快很多倍，还可以自定义图片质量

可惜是chrome插件，如果是picgo插件就好了。因为我想用vnote和vscode来写markdown笔记，通过picgo的pic-migrater插件将markdown里图片本地链接转成图床链接，发布到hexo博客。后期vs-picgo也会支持picgo的插件。

**Comment by xlzy520** [comment]
我尝试过bilibili的picgo插件，但是失败了，不知道是不是因为他的接口不支持流式文件，后面没精力了就没做下去了。
