### ISSUE TITLE
how to config picgo-core

### ISSUE THREAD

**Issue by tjx666** [xlzy520/picgo-plugin-smms-user#5]
Config the electron client is easy, but I feel a little complicated to config the picgo-core.

**Comment by xlzy520** [comment]
@tjx666 怎么说，不是很懂你的意思，是指这个插件配置复杂还是picgo core

**Comment by tjx666** [comment]
TL;DR：能在 README 里面说明下怎么在 picgo-core 中配置这个插件吗？

我一般使用的是 sm.ms 图床，然后 VSCode 的 picgo 扩展可以直接导入 pic-core 的配置文件，但是我看 pic-core 的文档看得有点迷，就想作者你能不能在 README 中给出一份 picgo-core 配置这个插件的例子。

**Comment by xlzy520** [comment]
@tjx666 picgo客户端有个搜索插件的地方，直接在那里搜过smms，就可以搜到了吧，然后安装重启就行了

**Comment by tjx666** [comment]
我的问题是 [picgo-core](https://picgo.github.io/PicGo-Core-Doc/zh/guide/config.html) 怎么配置，不是 picgo，我按照官方文档的配置方式配置了但是没用：

```json
{
  "picBed": {
    "current": "smms"
  },
  "picgoPlugins": {
    "picgo-plugin-smms-user": true
  },
  "picgo-plugin-smms-user": {
    "Authorization": "LDiubKZH5ZZX8wzpIKtcKY2q5hjAylMk"
  }
}
```

![screenshot_2020-03-02_18-56-23](https://user-images.githubusercontent.com/41773861/75670420-a7ab1880-5cb7-11ea-9484-5a7649cd4365.png)

**Comment by tjx666** [comment]
已解决，需要下面这样配置：
```json
{
  "picBed": {
    "uploader": "smms-user",
    "smms-user": {
      "Authorization": "LDiubKZH5ZZX8wzpIKtcKY2q5hjAylMk"
    }
  },
  "picgoPlugins": {
    "picgo-plugin-smms-user": true
  },
  "picgo-plugin-smms-user": {}
}
```

**Comment by xlzy520** [comment]
@tjx666 对不起，太久没用picgo了，没理解他们的区别
