### ISSUE TITLE
好像不能用了？

### ISSUE THREAD

**Issue by rayle2** [xlzy520/picgo-plugin-smms-user#6]
picgo2.2版本，一直上传失败。

**Comment by xlzy520** [comment]
有什么报错信息吗

**Comment by rayle2** [comment]
![QQ截图20200526225107](https://user-images.githubusercontent.com/17264314/82915533-733bb580-9fa3-11ea-9a58-1a7c0288ed89.jpg)

**Comment by Beta-y** [comment]
我的也是一直报错说API v1不能用，但是我已经用npm装了这个插件了，奇怪的是软甲界面里面又说我没装

**Comment by xlzy520** [comment]
@rayle2 @Beta-y 因为我转向我另外开发的哔哩哔哩图床去了，所以没有维护这个了。我之前是觉得sm.ms虽然免费，但是速度太慢。等最近有时间，我再更新一下看看。

**Comment by xlzy520** [comment]
https://github.com/Molunerfinn/PicGo/commit/3f3ea69cd6e55112372896bf1c38f2a2c9cb3b87

picgo作者现在提供了smms-v2，可以不用这个插件了，2.3版本

**Comment by Beta-y** [comment]
hhhhh我昨晚睡之前去下载2.3啦，一下就好了，不过还是谢谢啦！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XLZY"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 凌晨1:40
收件人: "xlzy520/picgo-plugin-smms-user"<picgo-plugin-smms-user@noreply.github.com&gt;; 
抄送: "贝塔"<1781767272@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xlzy520/picgo-plugin-smms-user] 好像不能用了？ (#6)





 
Molunerfinn/PicGo@3f3ea69
 
picgo作者现在提供了smms-v2，可以不用这个插件了，2.3版本

**Comment by Beta-y** [comment]
我升级2.3就好了！辛苦啦~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XLZY"<notifications@github.com&gt;; 
发送时间: 2020年6月11日(星期四) 凌晨0:53
收件人: "xlzy520/picgo-plugin-smms-user"<picgo-plugin-smms-user@noreply.github.com&gt;; 
抄送: "贝塔"<1781767272@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [xlzy520/picgo-plugin-smms-user] 好像不能用了？ (#6)





 
@rayle2 @Beta-y 因为我转向我另外开发的哔哩哔哩图床去了，所以没有维护这个了。我之前是觉得sm.ms虽然免费，但是速度太慢。等最近有时间，我再更新一下看看。

**Comment by zky001** [comment]
2.3版本直接填API验证code就能用了
