### ISSUE TITLE
上传失败，状态码503

### ISSUE THREAD

**Issue by amtoaer** [xlzy520/picgo-plugin-smms-user#7]
好像是因为cloudflare..
![2020-05-28_13-37.png](https://i.loli.net/2020/05/28/Vxo3awN9hqdu2HI.png)
![2020-05-28_13-37_1.png](https://i.loli.net/2020/05/28/w2PxJBq4gMTuHNI.png)

**Comment by xlzy520** [comment]
https://github.com/Molunerfinn/PicGo/commit/3f3ea69cd6e55112372896bf1c38f2a2c9cb3b87

picgo作者现在提供了smms-v2

**Comment by amtoaer** [comment]
好的，感谢！
